/*
 * Copyright (c) 2026 Tomasz Zurawski
 * SPDX-License-Identifier: AGPL-3.0-only
 */
package io.github.mgrtomaszzurawski.ksef.sdk.internal.runtime.batch;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.Objects;

/**
 * One encrypted part of a batch upload. Two implementations matching
 * the two {@link BatchAssemblyMode}s:
 *
 * <ul>
 *   <li>{@link OnDiskPart} — ciphertext lives in a temp file; {@link #cleanup()}
 *       deletes the file.</li>
 *   <li>{@link InMemoryPart} — ciphertext lives in a {@code byte[]} on the heap;
 *       {@link #cleanup()} is a no-op (GC).</li>
 * </ul>
 *
 * <p>Internal to the SDK transport layer — not part of the public,
 * Maven-Central-exported API surface (lives under
 * {@code sdk.internal.runtime.batch}, which is not exported by
 * {@code module-info.java}). The internal batch upload path
 * pattern-matches on the subtype to pick the right
 * {@code java.net.http.HttpRequest.BodyPublisher}.
 */
public sealed interface BatchPart {

    /** 1-based ordinal within the batch. */
    int ordinalNumber();

    /** Size of the encrypted bytes for this part. */
    long sizeBytes();

    /** SHA-256 of the encrypted bytes. */
    byte[] hash();

    /**
     * Release any resources held by this part. Idempotent and quiet —
     * a failed delete is logged but not propagated. Called automatically
     * by the internal batch submission flow; safe to call manually too.
     */
    void cleanup();

    /** Encrypted bytes streamed from disk. */
    record OnDiskPart(int ordinalNumber, long sizeBytes, byte[] hash, Path path) implements BatchPart {

        public OnDiskPart {
            Objects.requireNonNull(hash, "hash must not be null");
            Objects.requireNonNull(path, "path must not be null");
            hash = hash.clone();
        }

        @Override
        public byte[] hash() {
            return hash.clone();
        }

        @Override
        public void cleanup() {
            try {
                Files.deleteIfExists(path);
            } catch (IOException ignored) {
                // best effort — JVM exit hook is the safety net
            }
        }
    }

    /**
     * Encrypted bytes held in heap.
     *
     * <p><strong>Memory contract:</strong>
     * <ul>
     *   <li>The compact constructor defensively clones the supplied
     *       {@code bytes} so external mutation of the caller's array
     *       cannot affect this record's state.</li>
     *   <li>The {@link #bytes()} accessor (auto-generated by the record
     *       contract — overridden here) returns a defensive clone so
     *       returned-array mutation cannot affect the internal state.</li>
     *   <li>The hot upload path uses {@link #openStream()} instead of
     *       {@code bytes()}. The stream wraps the internal {@code byte[]}
     *       via {@link ByteArrayInputStream} — no copy, read-only by
     *       the {@link InputStream} contract.</li>
     * </ul>
     *
     * <p>Peak heap profile per 100 MiB part:
     * <ul>
     *   <li>Steady-state: 1× (the internal {@code byte[]}).</li>
     *   <li>During constructor: 2× transient (caller's input + clone),
     *       collapses to 1× when caller's reference goes out of scope.</li>
     *   <li>During upload via {@code openStream()}: 1× (no copy — the
     *       stream is a position pointer into the existing array).</li>
     * </ul>
     *
     * <p>The hash component (32 bytes, security-sensitive integrity
     * check) stays defensive on both ctor and accessor.
     */
    record InMemoryPart(int ordinalNumber, byte[] hash, byte[] bytes) implements BatchPart {

        public InMemoryPart {
            Objects.requireNonNull(hash, "hash must not be null");
            Objects.requireNonNull(bytes, "bytes must not be null");
            hash = hash.clone();
            bytes = bytes.clone();
        }

        @Override
        public long sizeBytes() {
            return bytes.length;
        }

        @Override
        public byte[] hash() {
            return hash.clone();
        }

        @Override
        public byte[] bytes() {
            return bytes.clone();
        }

        /**
         * Open a one-shot read-only stream over the ciphertext. Use this
         * from the upload path instead of {@link #bytes()} to avoid the
         * defensive clone — {@link InputStream}'s read-only contract
         * provides equivalent safety against external mutation without
         * the per-call copy.
         */
        public InputStream openStream() {
            return new ByteArrayInputStream(bytes);
        }

        @Override
        public void cleanup() {
            // GC — nothing to release.
        }

        /**
         * Equality by SHA-256 hash + ordinal — does NOT walk the bytes
         * payload (which can be up to 100 MB per part / 5 GiB across
         * a full batch). Two parts with matching ordinal and matching
         * SHA-256 are cryptographically equivalent (collision-resistant
         * hash); the explicit byte-level comparison the JDK record
         * default would emit is unnecessary and a memory-pressure
         * footgun for large batches.
         */
        @Override
        public boolean equals(Object o) {
            if (this == o) {
                return true;
            }
            if (!(o instanceof InMemoryPart other)) {
                return false;
            }
            return ordinalNumber == other.ordinalNumber
                    && Arrays.equals(hash, other.hash);
        }

        @Override
        public int hashCode() {
            int result = Integer.hashCode(ordinalNumber);
            result = 31 * result + Arrays.hashCode(hash);
            return result;
        }
    }
}
